// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calculate_scores_cpp
NumericVector calculate_scores_cpp(NumericVector values, NumericVector local_means, NumericVector local_sds);
RcppExport SEXP _localanomaly_calculate_scores_cpp(SEXP valuesSEXP, SEXP local_meansSEXP, SEXP local_sdsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type local_means(local_meansSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type local_sds(local_sdsSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_scores_cpp(values, local_means, local_sds));
    return rcpp_result_gen;
END_RCPP
}
// find_neighbours_cpp
List find_neighbours_cpp(int n);
RcppExport SEXP _localanomaly_find_neighbours_cpp(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(find_neighbours_cpp(n));
    return rcpp_result_gen;
END_RCPP
}
// local_statistics_cpp
List local_statistics_cpp(Rcpp::NumericVector x);
RcppExport SEXP _localanomaly_local_statistics_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(local_statistics_cpp(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_localanomaly_calculate_scores_cpp", (DL_FUNC) &_localanomaly_calculate_scores_cpp, 3},
    {"_localanomaly_find_neighbours_cpp", (DL_FUNC) &_localanomaly_find_neighbours_cpp, 1},
    {"_localanomaly_local_statistics_cpp", (DL_FUNC) &_localanomaly_local_statistics_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_localanomaly(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
