# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_scores_cpp <- function(values, local_means, local_sds) {
    .Call(`_localanomaly_calculate_scores_cpp`, values, local_means, local_sds)
}

find_neighbours_cpp <- function(n) {
    .Call(`_localanomaly_find_neighbours_cpp`, n)
}

local_statistics_cpp <- function(x) {
    .Call(`_localanomaly_local_statistics_cpp`, x)
}

